### PR TITLE
MVP REST API - Jun 23

### PR DESCRIPTION
**Pull request by ItsThompson**
**Example inputs to use:**
Read user_id from username: /v1/user/id/johndoe0
Get user information from user_id: /v1/user/info/0
Use login with username, password: /v1/user/login
Read song information from song_id: /v1/song/info/0
Get user_preferences from user_id: /v1/user_preferences/id/0/
Insert record into user_preference: /v1/user_preferences/new
Updates record into user_preferences: /v1/user_preferences/update

### CODE REVIEW

**Comment by ItsThompson** [comment]
@aagrawal05 Wanna take a look?

**Comment by ItsThompson** [comment]
> #### ⚠️ GitGuardian has uncovered 1 secret following the scan of your pull request.
> Please consider investigating the findings and remediating the incidents. Failure to do so may lead to compromising the associated services or software components.
> 
> 🔎 Detected hardcoded secret in your pull request
> 🛠 Guidelines to remediate hardcoded secrets
> 🦉 [GitGuardian](https://dashboard.gitguardian.com/auth/login/?utm_medium=checkruns&utm_source=github&utm_campaign=cr1) detects secrets in your source code to help developers and security teams secure the modern development process. You are seeing this because you or someone else with access to this repository has authorized GitGuardian to scan your pull request.Our GitHub checks need improvements? [Share your feedbacks](https://050127dayho.typeform.com/to/KmeAPTMk)!

@aagrawal05 I assume this is a false positive right?

**Comment by aagrawal05** [comment]
Ight lemme check.

**Comment by aagrawal05** [comment]
Idk, found this token in `./node_modules/debug/.coveralls.yml` repo_token: SIAeZjKYlHK74rbcFvNHMUzjRiMpflxve. Conclusion: It may be a positive, but an incredibly easy one to fix. I'll add it to .gitignore.

**Pull request merged**
